[package]
name = "vk-save"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Parsing di rksys.dat, RFL_DB.dat e blocchi Mii Wii."

[dependencies]
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true
md-5 = "0.10"

[dev-dependencies]
tempfile.workspace = true
