<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<ApplicationIcon>Assets/app.ico</ApplicationIcon>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>VanzaKart Launcher</AssemblyName>
    <RootNamespace>VanzaKartLauncher</RootNamespace>
    <Version>1.4.5</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Assets\app.ico" />
    <None Remove="Assets\discord.png" />
    <None Remove="Assets\logo-cerchio.png" />
    <None Remove="Assets\logo-quadrato.png" />
    <None Remove="Assets\logo.png" />
    <None Remove="Assets\website.png" />
    <None Remove="Assets\mii_silhouette.png" />
    <None Remove="logo.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\app.ico" />
    <Resource Include="Assets\logo-cerchio.png" />
    <Resource Include="Assets\logo-quadrato.png" />
    <Resource Include="Assets\logo.png" />
    <Resource Include="Assets\mii_silhouette.png" />
  </ItemGroup>



  <ItemGroup>
    <Resource Include="Assets\discord.png" />
    <Resource Include="Assets\website.png" />
    <Resource Include="logo.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="1.0.0" />
  </ItemGroup>

  <Target Name="RemoveRuntimeUserDataFromPublish" AfterTargets="Publish">
    <ItemGroup>
      <RuntimeUserData Include="$(PublishDir)launcher_settings.json" />
      <RuntimeUserData Include="$(PublishDir)user_preferences.json" />
      <RuntimeUserData Include="$(PublishDir)mod_version.txt" />
      <RuntimeUserData Include="$(PublishDir)mod_beta_version.txt" />
      <RuntimeUserData Include="$(PublishDir)musicpack_version.txt" />
      <RuntimeUserData Include="$(PublishDir)musicpack_beta_version.txt" />
      <RuntimeUserData Include="$(PublishDir)mod_install_state.json" />
      <RuntimeUserData Include="$(PublishDir)VanzaKart_launcher.json" />
      <RuntimeUserData Include="$(PublishDir)VKBeta_launcher.json" />
    </ItemGroup>
    <Delete Files="@(RuntimeUserData)" />
  </Target>
</Project>
